### ISSUE TITLE
Error on main page from news 1.7beta 2

### ISSUE THREAD

**Issue by alain01** [XoopsModules25x/news#17]
Error: Error: Call to undefined function news_getmoduleoption() in file /modules/news/index.php line 227

News 1.7Beta2

XOOPS Version | XOOPS 2.5.9
-- | --
PHP Version | 7.0.3
mySQL Version | 5.7.11
Server API | apache2handler
OS | WINNT
fsockopen | On
post_max_size | 8M
max_input_time | 60
output_buffering | 4096
max_execution_time | 30
memory_limit | 128M
file_uploads | On
upload_max_filesize | 2M

**Comment by mambax7** [comment]
Thanks! It's fixed in: https://github.com/XoopsModules25x/news/pull/18
