### ISSUE TITLE
Unknown: Object of class XoopsFormSelect could not be converted to string in file news_block_topics.tpl.php line 5

### ISSUE THREAD

**Issue by alain01** [XoopsModules25x/news#19]
Unknown: Object of class XoopsFormSelect could not be converted to string in file -secure/xoops_data/caches/smarty_compile/86a9106a-news-dzoni-2012-default^%%83^830^830A39F5%%db%3Anews_block_topics.tpl.php line 5

Try with different themes, same issue.
XOOPS 2.5.9

**Comment by alain01** [comment]
humm,
for my sandbox, i used 
/xoops259-secure/xoops_data
/xoops259-secure/xoops_lib

and i read the error message : could not be converted to string in file -secure/xoops_data/
not 
could not be converted to string in file xoops259-secure/xoops_data/

May be the problem is here ?

**Comment by mambax7** [comment]
Thanks for reporting. I'll check later tonight if I can reproduce it. 
What theme are you using? Can you test it with the Default and with xBootstrap?

**Comment by mambax7** [comment]
Do you have any articles there? I kind of recall that I had an issue like this, but there was no items in the database. So make sure that you have a category and articles there that have the permissions to be visible

**Comment by alain01** [comment]
Same issue with both themes Default and with xBootstrap.
There is 1 category and 1 article, both are enabled for all groups (webmasters, users, anonymous) for view.

**Comment by mambax7** [comment]
OK, let me install it fresh on another system...

**Comment by mambax7** [comment]
Fixed in: https://github.com/XoopsModules25x/news/pull/20
