### ISSUE TITLE
expand the size of the "image" column

### ISSUE THREAD

**Issue by montuy337513** [XoopsModules25x/news#25]
to allow the use of SEO Picture, during the next update, the width of the "picture" column should be increased
picture VARCHAR (50) ---> picture VARCHAR (255)

**Comment by mambax7** [comment]
Addressed in https://github.com/XoopsModules25x/news/pull/27
Please check if it works for you, if not, please re-open. 
Please note: News is not actively maintained anymore.  Please use Publisher
