### ISSUE TITLE
Debug smarty tpl warnings in PHP 8.0.24

### ISSUE THREAD

**Issue by jorgenqv** [XoopsModules25x/news#35]
XOOPS Version | XOOPS 2.5.11-Beta2 from Master latest update sept 28, 2022
PHP Version | 8.0.24
MySQL Version | 10.3.36-MariaDB-1:10.3.36+maria~ubu2004
Server API | cgi-fcgi
OS | Linux
fsockopen | On
post_max_size | 256M
max_input_time | 60
output_buffering |  
max_execution_time | 300
memory_limit | 2147483648
file_uploads | On
upload_max_filesize | 256M

Default theme

News module version 1.72.0

Getting debug warnings bellow, works fine otherwise

Warning: Undefined array key "topic_rssfeed_link" in file /path/to/my/private_xoops_data/caches/smarty_compile/e897619a-news-default-default^%%54^543^54315394%%db%3Anews_index.tpl.php line 4
Warning: Undefined array key "topic_description" in file /path/to/my/private_xoops_data/caches/smarty_compile/e897619a-news-default-default^%%54^543^54315394%%db%3Anews_index.tpl.php line 22
Warning: Undefined array key "subtitle" in file /path/to/my/private_xoops_data/caches/smarty_compile/e897619a-news-default-default^%%27^27C^27CCF40B%%db%3Anews_item.tpl.php line 11
Warning: Undefined array key "news_by_the_same_author_link" in file /path/to/my/private_xoops_data/caches/smarty_compile/e897619a-news-default-default^%%27^27C^27CCF40B%%db%3Anews_item.tpl.php line 26
Warning: Undefined array key "lang_topic" in file /path/to/my/private_xoops_data/caches/smarty_compile/e897619a-news-default-default^%%27^27C^27CCF40B%%db%3Anews_item.tpl.php line 28
Warning: Undefined array key "subtitle" in file /path/to/my/private_xoops_data/caches/smarty_compile/e897619a-news-default-default^%%27^27C^27CCF40B%%db%3Anews_item.tpl.php line 11
Warning: Undefined array key "news_by_the_same_author_link" in file /path/to/my/private_xoops_data/caches/smarty_compile/e897619a-news-default-default^%%27^27C^27CCF40B%%db%3Anews_item.tpl.php line 26
Warning: Undefined array key "lang_topic" in file /path/to/my/private_xoops_data/caches/smarty_compile/e897619a-news-default-default^%%27^27C^27CCF40B%%db%3Anews_item.tpl.php line 28
Warning: Undefined array key "subtitle" in file /path/to/my/private_xoops_data/caches/smarty_compile/e897619a-news-default-default^%%27^27C^27CCF40B%%db%3Anews_item.tpl.php line 11
Warning: Undefined array key "news_by_the_same_author_link" in file /path/to/my/private_xoops_data/caches/smarty_compile/e897619a-news-default-default^%%27^27C^27CCF40B%%db%3Anews_item.tpl.php line 26
Warning: Undefined array key "lang_topic" in file /path/to/my/private_xoops_data/caches/smarty_compile/e897619a-news-default-default^%%27^27C^27CCF40B%%db%3Anews_item.tpl.php line 28
Warning: Undefined array key "subtitle" in file /path/to/my/private_xoops_data/caches/smarty_compile/e897619a-news-default-default^%%27^27C^27CCF40B%%db%3Anews_item.tpl.php line 11
Warning: Undefined array key "news_by_the_same_author_link" in file /path/to/my/private_xoops_data/caches/smarty_compile/e897619a-news-default-default^%%27^27C^27CCF40B%%db%3Anews_item.tpl.php line 26
Warning: Undefined array key "lang_topic" in file /path/to/my/private_xoops_data/caches/smarty_compile/e897619a-news-default-default^%%27^27C^27CCF40B%%db%3Anews_item.tpl.php line 28
Warning: Undefined array key "subtitle" in file /path/to/my/private_xoops_data/caches/smarty_compile/e897619a-news-default-default^%%27^27C^27CCF40B%%db%3Anews_item.tpl.php line 11
Warning: Undefined array key "news_by_the_same_author_link" in file /path/to/my/private_xoops_data/caches/smarty_compile/e897619a-news-default-default^%%27^27C^27CCF40B%%db%3Anews_item.tpl.php line 26
Warning: Undefined array key "lang_topic" in file /path/to/my/private_xoops_data/caches/smarty_compile/e897619a-news-default-default^%%27^27C^27CCF40B%%db%3Anews_item.tpl.php line 28

**Comment by mambax7** [comment]
most of them should be fixed in https://github.com/XoopsModules25x/news/pull/38/
If you see any remaining or new ones, please open a new issue.

Thank you for testing and reporting!
