### ISSUE TITLE
Internal server error on Admin About tab

### ISSUE THREAD

**Issue by jorgenqv** [XoopsModules25x/news#37]
XOOPS Version | XOOPS 2.5.11-Beta2 from Master latest update sept 28, 2022
PHP Version | 8.0.24
MySQL Version | 10.3.36-MariaDB-1:10.3.36+maria~ubu2004
Server API | cgi-fcgi
OS | Linux
fsockopen | On
post_max_size | 256M
max_input_time | 60
output_buffering |  
max_execution_time | 300
memory_limit | 2147483648
file_uploads | On
upload_max_filesize | 256M

Default theme

News module version 1.72.0

When going to Admin in the News Admin backend and clicking on About tab I get

A problem has occurred on our server!
Page is currently unavailable
We are working on a fix
Please come back soon ...

Error : TypeError: mktime(): Argument #4 ($month) must be of type ?int, string given
Backtrace:

Errors
Warning: Undefined array key 2 in file /Frameworks/moduleclasses/moduleadmin/moduleadmin.php line 506
Error: TypeError: mktime(): Argument #4 ($month) must be of type ?int, string given in file /Frameworks/moduleclasses/moduleadmin/moduleadmin.php line 506

**Comment by montuy337513** [comment]
bug in line 31 of the xoops_version.php file
replace 
`$modversion['release_date']  = '2022/02-20';`

by 

`$modversion['release_date']  = '2022/02/20';`

**Comment by mambax7** [comment]
Fixed in https://github.com/XoopsModules25x/news/pull/38/
